/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.zeus.offernotificator

import com.google.common.io.Resources.getResource
import java.awt.SystemTray
import java.awt.Toolkit
import java.awt.TrayIcon

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    val offerSearcher = OfferSearcher()

    offerSearcher.startDaemon()
}
