/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.zeus.offernotificator


fun main() {
    println("Zeus offerNotificator")

    val offerSearcher = OfferSearcher()

    offerSearcher.startDaemon()
}
